# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy to various OSes
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller
    - name: Build and publish on Windows
      env:
        PASS: ${{ secrets.SECRET_PASS_WORD }}
      run: |
        pyinstaller qmlview.spec
        python uploader.py ${{ matrix.os }} "AFricaistoolong@#16"
      if: ${{ matrix.os }} == 'windows.latest'
    - name: Build and publish on Unix
      env:
        PASS: ${{ secrets.SECRET_PASS_WORD }}
      run: |
        pyinstaller qmlview.spec
        python uploader.py ${{ matrix.os }} "AFricaistoolong@#16"
      if: ${{ matrix.os }} == 'ubuntu-latest' || ${{ matrix.os }} == 'macOS-latest'
